version: '3.8'
networks:
  server-network:
    driver: bridge
# docker compose -f docker-compose-dev.yml up -d
# docker compose -f docker-compose-dev.yml build
# docker compose -f docker-compose-dev.yml down


services:
  # client:
  #     build: ./ClientAvalonia
  #     networks:
  #       - server-network
  # # important: not exposing ports so the server only listen to docker containers in his network
  nginx:
    build: ./nginx/dev
    ports:
      - '80:80'
      - '443:443'
    networks:
      - server-network

  db:
    image: postgres:15.2
    ports:
      - '5432:5432' # used with pgadmin
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - server-network
    volumes:
      - ./database/postgresql:/var/lib/postgresql/data
      
    ######################################
  backendserver:
    build: ./BackendServer
    # only apply in dev mode and test with http://localhost/swagger
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      BASE_URL: http://localhost
      RUNNING_IN_DOCKER: true
      APP_PASSWORD: ${APP_PASSWORD}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID_SANDBOX}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET_SANDBOX}
      PAYPAL_MODE: sandbox
    ######################################
    #scale: 5
    depends_on:
      - db
    networks:
      - server-network

  # for orleans clustering
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - server-network

  client:
    build: ./client
    networks:
      - server-network